const Colors = {
    PROGRESS_BAR_BLUE: '#14AAF5',
    BOOKMARKS_BACKGROUND: '#1f4e5b',
    BOOKMARKS_ELEMENT_BACKGROUND: '#4B4C4C',
    BOOKMARKS_ELEMENT_SELECTED_BACKGROUND: '#1C1B1B',
    BOOKMARKS_TEXT: '#14AAF5',
    DEFAULT_GREY: '#4B4C4C',
    PROGRESS_BAR_TEXT: '#F0F0F0'
};

export default Colors;