const Colors = {
    PROGRESS_BAR_BLUE: '#14AAF5',
    PROGRESS_BAR_TEXT: '#F0F0F0',

    BOOKMARKS_BACKGROUND: '#1f4e5b',
    BOOKMARKS_ELEMENT_BACKGROUND: '#4B4C4C',
    BOOKMARKS_ELEMENT_SELECTED_BACKGROUND: '#2E2F2F',
    BOOKMARKS_TEXT: '#14AAF5',

    // Utils
    DEFAULT_GREY: '#4B4C4C',
    BOX_SHADOW: '0px 0px 2.5px 0',


    EXAMPLES_BACKGROUND: '#FFFFFF',
    EXAMPLES_CONTAINER_BACKGROUND: '#F4F6F8',

    NAVIGATION_WORD_BACKGROUND: 'rgb(215, 215, 215)',
    NAVIGATION_WORD_BACKGROUND_HOVER: '#a2a5a2',
    NAVIGATION_WORD_CONTAINER_BACKGROUND: '#f1f1f1',
    DELETE_ELEM_ICON: '#dc3545',
    FAV_ELEM_ICON: '#FFD700'


};

export default Colors;